### ISSUE TITLE
Generate PLY or OBJ file

### ISSUE THREAD

**Issue by jiangyijin** [tpark94/sat-sq-recon#2]
Could you please tell me how to generate a PLY or OBJ file for the superquadric mesh at the end, and how to create a point cloud file corresponding to the superquadric mesh as shown in the paper?

**Comment by tpark94** [comment]
We use the pytorch3d library, so I'm sure you can use something like `pytorch3d.io.save_obj` to save the OBJ file. 

https://pytorch3d.readthedocs.io/en/latest/modules/io.html

**Comment by wuaodi** [comment]
add some code to evaluate.py

```
# Inference
mesh_pr, pcl_pr, mask_pr, occupancy_pr, metrics = inference(args, cfg, net, batch)

# add
from pytorch3d.io import save_obj
for i, mesh in enumerate(mesh_pr):
        save_obj(
            str(save_dir / f'primitive_{i}.obj'),
            verts=mesh.verts_list()[0],
            faces=mesh.faces_list()[0]
        )

# you can use cloudcompare to check the result
```
